SELECT 	dbo.DWFEI_BRANCH_VENDOR_DIMENSION.ACCOUNT_NAME, 
		dbo.DWFEI_BRANCH_VENDOR_DIMENSION.VENDOR_NK, 
		dbo.DWFEI_BRANCH_VENDOR_DIMENSION.ALPHA, 
		dbo.DWFEI_BRANCH_VENDOR_DIMENSION.VENDOR_NAME, 
		dbo.DWFEI_BRANCH_VENDOR_DIMENSION.TERMS, 
		ISNULL ((SELECT dbo.DWFEI_AP_TERMS_DIMENSION.DESCRIPTION 
				 FROM DWFEI_AP_TERMS_DIMENSION 
				 WHERE DWFEI_AP_TERMS_DIMENSION.TERMS_NK = DWFEI_BRANCH_VENDOR_DIMENSION.TERMS),'') TERMS_DESCRIPTION, 
		ISNULL (dbo.DWFEI_BRANCH_VENDOR_DIMENSION.ADDRESS1,'') ADDRESS1, 
		ISNULL (dbo.DWFEI_BRANCH_VENDOR_DIMENSION.ADDRESS2,'') ADDRESS2, 
		ISNULL (dbo.DWFEI_BRANCH_VENDOR_DIMENSION.CITY,'') CITY, 
		ISNULL (dbo.DWFEI_BRANCH_VENDOR_DIMENSION.STATE,'') STATE, 
		ISNULL (dbo.DWFEI_BRANCH_VENDOR_DIMENSION.TERR_PROV,'')TERR_PROV, 
		ISNULL (dbo.DWFEI_BRANCH_VENDOR_DIMENSION.COUNTRY,'') COUNTRY, 
		ISNULL (dbo.DWFEI_BRANCH_VENDOR_DIMENSION.ZIP, '') ZIP, 
		ISNULL(dbo.DWFEI_BR_VENDOR_PURCHASE_FACT.AP_BAL,0) AP_BAL, 
		dbo.DWFEI_BRANCH_VENDOR_DIMENSION.FROZEN_REASON


FROM dbo.DWFEI_BRANCH_VENDOR_DIMENSION 
	LEFT JOIN dbo.DWFEI_BR_VENDOR_PURCHASE_FACT
	ON dbo.DWFEI_BRANCH_VENDOR_DIMENSION.VENDOR_GK = dbo.DWFEI_BR_VENDOR_PURCHASE_FACT.VENDOR_GK

WHERE dbo.DWFEI_BR_VENDOR_PURCHASE_FACT.AP_BAL > 0
	AND dbo.DWFEI_BRANCH_VENDOR_DIMENSION.FROZEN = 'Y'
	AND (dbo.DWFEI_BRANCH_VENDOR_DIMENSION.ACCOUNT_NAME NOT IN (SELECT DWFEI_ACCOUNT_NAME_ACCESS.ana_ACCOUNT_NAME 
																FROM [dbo].DWFEI_ACCOUNT_NAME_ACCESS 
																WHERE DWFEI_ACCOUNT_NAME_ACCESS.ana_ACCESS = 'N' 
																	OR DWFEI_ACCOUNT_NAME_ACCESS.ana_REPORT = 'N') 
																	AND dbo.DWFEI_BRANCH_VENDOR_DIMENSION.ACCOUNT_NUMBER_NK NOT IN ('300','396','659','664','703','720','659','1000','1184','1314'))

ORDER BY AP_BAL DESC